In [2]:
import nltk
import pandas as pd
import numpy as np

In [25]:
stream_df = pd.read_csv('Northernlion_Full.csv',index_col=None, header=0)
stream_df.drop('GamesPlayed',axis=1, inplace=True)
stream_df

,RowNum,StartTime,EndTime,ViewsGained,FollowersGained,MaxViewers,AverageViewers,FollowersPerHour,ViewsPerHour,LengthMinutes
0,1,2017-09-21 21:15:00.000,2017-09-22 00:15:00.000,5984,36,5390,4636,2.77,460.31,195
1,2,2017-09-20 21:15:00.000,2017-09-21 00:00:00.000,4881,49,5988,5245,4.08,406.75,180
2,3,2017-09-19 20:45:00.000,2017-09-19 23:15:00.000,2160,48,3319,2718,4.36,196.36,165
3,4,2017-09-18 22:15:00.000,2017-09-19 01:15:00.000,4793,45,5325,4911,3.46,368.69,195
4,5,2017-09-17 20:30:00.000,2017-09-17 23:30:00.000,3380,97,3527,3074,7.46,260.00,195
5,6,2017-09-14 21:15:00.000,2017-09-15 00:15:00.000,4818,51,5363,4562,3.92,370.62,195
6,7,2017-09-13 21:15:00.000,2017-09-14 00:15:00.000,6174,48,5601,4596,3.69,474.92,195
7,8,2017-09-12 20:15:00.000,2017-09-12 23:00:00.000,3881,52,2980,2557,4.33,323.42,180
8,9,2017-09-11 22:00:00.000,2017-09-12 01:15:00.000,3478,89,5555,4683,6.36,248.43,210
9,10,2017-09-10 20:30:00.000,2017-09-10 23:30:00.000,5416,174,3604,3304,13.38,416.62,195
10,11,2017-09-07 21:15:00.000,2017-09-08 00:30:00.000,6323,81,5639,4498,5.79,451.64,210
11,12,2017-09-06 21:15:00.000,2017-09-07 00:15:00.000,5880,110,5872,5153,8.46,452.31,195
12,13,2017-09-06 00:45:00.000,2017-09-06 04:00:00.000,2102,31,3039,2731,2.21,150.14,210
13,14,2017-08-30 21:15:00.000,2017-08-31 00:15:00.000,1818,23,4977,3334,1.77,139.85,195
14,15,2017-08-29 20:15:00.000,2017-08-29 23:30:00.000,3943,55,3062,2554,3.93,281.64,210
15,16,2017-08-28 22:15:00.000,2017-08-29 01:15:00.000,5398,140,6405,5767,10.77,415.23,195
16,17,2017-08-27 20:15:00.000,2017-08-27 23:15:00.000,7595,265,4295,3857,20.38,584.23,195
17,18,2017-08-24 21:15:00.000,2017-08-25 00:15:00.000,5400,91,5751,4715,7.00,415.38,195
18,19,2017-08-23 21:15:00.000,2017-08-24 00:15:00.000,5962,170,6185,5214,13.08,458.62,195
19,20,2017-08-22 20:30:00.000,2017-08-22 23:45:00.000,6584,133,4089,3576,9.50,470.29,210
20,21,2017-08-21 22:15:00.000,2017-08-22 01:15:00.000,5065,95,5347,4797,7.31,389.62,195
21,22,2017-08-20 20:15:00.000,2017-08-20 23:15:00.000,4417,325,4388,3920,25.00,339.77,195
22,23,2017-08-17 21:15:00.000,2017-08-18 00:15:00.000,5365,108,6075,5214,8.31,412.69,195
23,24,2017-08-16 21:15:00.000,2017-08-17 00:30:00.000,5823,116,5250,4681,8.29,415.93,210
24,25,2017-08-15 20:15:00.000,2017-08-15 23:15:00.000,3798,84,3343,2514,6.46,292.15,195
25,26,2017-08-14 22:15:00.000,2017-08-15 01:15:00.000,4971,156,6094,5294,12.00,382.38,195
26,27,2017-08-13 20:30:00.000,2017-08-13 23:45:00.000,4866,429,5714,4821,30.64,347.57,210
27,28,2017-08-11 20:15:00.000,2017-08-11 23:15:00.000,3784,73,3351,2706,5.62,291.08,195
28,29,2017-08-10 21:15:00.000,2017-08-11 00:15:00.000,5089,99,5301,4374,7.62,391.46,195
29,30,2017-08-07 22:15:00.000,2017-08-08 01:15:00.000,6552,189,6025,5453,14.54,504.00,195
...,...,...,...,...,...,...,...,...,...,...
411,412,2015-09-10 22:15:00.000,2015-09-11 01:00:00.000,4835,68,5900,4736,5.67,402.92,180
412,413,2015-09-09 22:15:00.000,2015-09-10 01:00:00.000,5387,157,6170,5269,13.08,448.92,180
413,414,2015-09-07 22:15:00.000,2015-09-08 01:00:00.000,5552,169,6131,5282,14.08,462.67,180
414,415,2015-09-06 22:30:00.000,2015-09-07 01:00:00.000,4529,359,7786,4528,32.64,411.73,165
415,416,2015-09-06 19:15:00.000,2015-09-06 21:45:00.000,2548,64,3438,2724,5.82,231.64,165
416,417,2015-09-05 19:30:00.000,2015-09-05 21:45:00.000,2694,163,3671,2528,16.30,269.40,150
417,418,2015-09-03 22:15:00.000,2015-09-04 01:00:00.000,5033,72,5226,4784,6.00,419.42,180
418,419,2015-09-02 21:15:00.000,2015-09-03 00:00:00.000,5032,118,5542,4878,9.83,419.33,180
419,420,2015-08-24 22:15:00.000,2015-08-25 01:15:00.000,4069,95,4747,4022,7.31,313.00,195
420,421,2015-08-23 21:30:00.000,2015-08-24 00:45:00.000,7992,794,9604,6503,56.71,570.86,210
421,422,2015-08-23 18:15:00.000,2015-08-23 20:45:00.000,3226,137,3427,2835,12.45,293.27,165
422,423,2015-08-20 22:00:00.000,2015-08-21 01:00:00.000,5916,201,6760,5037,15.46,455.08,195
423,424,2015-08-19 21:15:00.000,2015-08-20 00:00:00.000,6289,271,7031,5968,22.58,524.08,180
424,425,2015-08-17 22:15:00.000,2015-08-18 01:00:00.000,6949,236,7193,6444,19.67,579.08,180
425,426,2015-08-16 20:15:00.000,2015-08-16 23:00:00.000,3317,123,4410,3869,10.25,276.42,180
426,427,2015-08-13 22:15:00.000,2015-08-14 01:00:00.000,5644,217,7477,5918,18.08,470.33,180
427,428,2015-08-12 21:15:00.000,2015-08-13 00:00:00.000,6472,151,6501,5995,12.58,539.33,180
428,429,2015-08-10 22:15:00.000,2015-08-11 01:00:00.000,6630,224,7333,6101,18.67,552.50,180
429,430,2015-08-09 20:15:00.000,2015-08-09 23:00:00.000,3381,141,4443,3963,11.75,281.75,180
430,431,2015-08-06 22:15:00.000,2015-08-07 01:15:00.000,5650,203,6253,5518,15.62,434.62,195
431,432,2015-08-05 21:15:00.000,2015-08-06 00:00:00.000,7056,235,6660,5136,19.58,588.00,180
432,433,2015-08-03 22:15:00.000,2015-08-04 01:15:00.000,6322,125,6565,5163,9.62,486.31,195
433,434,2015-08-02 20:15:00.000,2015-08-02 23:00:00.000,3800,137,4507,3715,11.42,316.67,180
434,435,2015-07-30 22:15:00.000,2015-07-31 01:00:00.000,6798,146,5874,4860,12.17,566.50,180
435,436,2015-07-30 00:30:00.000,2015-07-30 01:00:00.000,1550,60,4227,3392,12.00,310.00,75
436,437,2015-07-29 22:15:00.000,2015-07-30 00:00:00.000,5050,169,4308,3749,15.36,459.09,165
437,438,2015-07-27 22:15:00.000,2015-07-28 01:00:00.000,8887,181,6658,5865,15.08,740.58,180
438,439,2015-07-26 20:15:00.000,2015-07-26 23:00:00.000,4120,132,3758,3171,11.00,343.33,180
439,440,2015-07-20 01:00:00.000,2015-07-20 03:30:00.000,3967,131,3834,3060,11.91,360.64,165
440,441,2015-07-19 20:15:00.000,2015-07-19 22:45:00.000,6153,208,5440,4480,18.91,559.36,165

In [ ]:
#Create Date Col as Month DD, YYYY
formatted = []
order = [1,0,2]
for date in stream_df['Stream start time']:
    dmy = date.split(' ')[1:-1] #Date/Month/Year
    dmy[0] = dmy[0][:-2] #Remove day suffixes
    mdy = [dmy[i] for i in order]
    formatted.append(str(mdy[0] + " " + mdy[1] + ", " + mdy[2]))
formatted[:15]